### ISSUE TITLE
Problem in GWLP function for non-mixed arrays with more than two levels

### ISSUE THREAD

**Issue by ABohynDOE** [eendebakpt/oapackage#214] opened 2022-09-12 20:33 UTC
In the GWLP function:
https://github.com/eendebakpt/oapackage/blob/21b016a9ca6154b068bf478ec800f54140291840/src/arrayproperties.cpp#L519-L535
There are two subfunctions that can be used depending on the array provided:
- `GWLP_two_level_design` for two-level arrays
- `GWLPmixed` for mixed-arrays

The check is done through the function `al.is_mixed_level()` for an array `al`.
However, when the array is not mixed but is not a two-level design (e.g. an array with several three-level factors), `al.is_mixed_level()` returns `False`, and `GWLP_two_level_design` is used when `GWLPmixed` should be used.

I recommend changing the `al.is_mixed_level()` to output `False` for two-level arrays and not for all non-mixed arrays.

**Comment by eendebakpt** [comment] 2022-09-13 09:38
Thanks for the report. The issue is fixed in https://github.com/eendebakpt/oapackage/pull/215.

**Closed by eendebakpt** 2022-09-13 09:38 UTC
